#include<iostream>
#include<conio.h>
#include<math.h>
using namespace std;
int main()
{
 int i;
 cout<<"Enter the desired number"<<'\n';
 cin>>i;
 cout<<'\n'<<"Table of " <<i<<'\n';
 cout<<i <<"*1=" <<i*1 <<'\n';
 cout<<i <<"*2=" <<i*2 <<'\n';
 cout<<i <<"*3=" <<i*3 <<'\n';
 cout<<i <<"*4=" <<i*4 <<'\n';
 cout<<i <<"*5=" <<i*5 <<'\n';
 cout<<i <<"*6=" <<i*6 <<'\n';
 cout<<i <<"*7=" <<i*7 <<'\n';
 cout<<i <<"*8=" <<i*8 <<'\n';
 cout<<i <<"*9=" <<i*9 <<'\n';
 cout<<i <<"*10=" <<i*10 <<'\n';
 cout<<i <<'*'<<i<<'=' <<pow(i,i);
 return 0;
}
